# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# copied from https://github.com/circleci/circleci-images/issues/168#issuecomment-372046916
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - cache-

      - run:
          name: install dependencies
          command: pipenv sync

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: cache-{{ checksum "Pipfile.lock" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: pipenv run python manage.py test